# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthenticatorDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthenticatorDemo
  pod 'AFNetworking'
  pod 'MBProgressHUD'

  target 'AuthenticatorDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuthenticatorDemoUITests' do
    # Pods for testing
  end

end
