# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthenticatorKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthenticatorKit
  pod 'AFNetworking', '~> 3.2.1'

  target 'AuthenticatorKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuthenticatorKitUITests' do
    # Pods for testing
  end

end
