# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AuthenticatorKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthenticatorKitDemo
  pod 'AuthenticatorKit'
  pod 'MBProgressHUD'

  target 'AuthenticatorKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AuthenticatorKitDemoUITests' do
    # Pods for testing
  end

end
